name: worker
dependencies:
- python
- pip
- imageio
- rasterio
- numpy>=1.16.6,<1.20.0
- pydot>=1.4.2,<2
- scipy>=1.2.3,<2
- scikit-image=0.18.0
- scikit-learn>=0.20.4
- jupyter>=1.0.0,<2
- opencv<5
#- pip:
  # -
