#!/usr/bin/env bash
# Claude Code PostToolUse hook — regenerates worker docs when a PR is created.
#
# Triggers after any Bash tool call. Checks whether the command was a
# "gh pr create" invocation; if so, regenerates all worker .md files and
# registry.md, then commits and pushes the changes to the current branch so
# that the PR includes up-to-date documentation.
#
# Hook input (stdin): JSON from Claude Code with shape:
#   { "tool_name": "Bash", "tool_input": { "command": "..." }, ... }

set -euo pipefail

# ── 1. Parse stdin ────────────────────────────────────────────────────────────
INPUT="$(cat)"

# Extract the bash command that was run (requires python3 or jq)
if command -v python3 &>/dev/null; then
    BASH_CMD="$(echo "$INPUT" | python3 -c "
import json, sys
data = json.load(sys.stdin)
print(data.get('tool_input', {}).get('command', ''))
" 2>/dev/null || true)"
elif command -v jq &>/dev/null; then
    BASH_CMD="$(echo "$INPUT" | jq -r '.tool_input.command // ""' 2>/dev/null || true)"
else
    exit 0
fi

# ── 2. Check whether this was a PR creation ───────────────────────────────────
if ! echo "$BASH_CMD" | grep -qE 'gh pr (create|edit)'; then
    exit 0
fi

echo "[update-worker-docs] PR operation detected — regenerating worker documentation..."

# ── 3. Locate repo root ───────────────────────────────────────────────────────
REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

# ── 4. Run the documentation generator ───────────────────────────────────────
if ! python3 generate_worker_docs.py; then
    echo "[update-worker-docs] ERROR: generate_worker_docs.py failed — skipping commit." >&2
    exit 0
fi

# ── 5. Commit changes if any ──────────────────────────────────────────────────
if git diff --quiet && git diff --cached --quiet; then
    echo "[update-worker-docs] Documentation is already up to date."
    exit 0
fi

echo "[update-worker-docs] Documentation changed — committing..."
git add registry.md
git add 'workers/**/*.md'
# Stage any newly created .md files too
git add --all -- '*.md' 'workers' 2>/dev/null || true

git commit -m "docs: auto-update worker docs and registry.md

Regenerated by the update-worker-docs Claude Code hook after PR creation."

# ── 6. Push to the current branch ────────────────────────────────────────────
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "[update-worker-docs] Pushing docs update to origin/$BRANCH..."

for ATTEMPT in 1 2 3 4; do
    if git push origin "$BRANCH"; then
        echo "[update-worker-docs] Done — documentation pushed to origin/$BRANCH."
        exit 0
    fi
    WAIT=$(( ATTEMPT * 2 ))
    echo "[update-worker-docs] Push attempt $ATTEMPT failed; retrying in ${WAIT}s..." >&2
    sleep "$WAIT"
done

echo "[update-worker-docs] ERROR: Could not push after 4 attempts." >&2
exit 0   # Non-fatal: don't block the PR creation
