#!/usr/bin/env bash
# Claude Code PostToolUse hook — regenerates worker docs when a PR is created.
#
# Triggers after any Bash tool call. Checks whether the command was a
# "gh pr create"/"gh pr edit" invocation AND whether the branch actually
# changed worker source (workers/ or generate_worker_docs.py) vs. the base; if
# so, regenerates all worker .md files and registry.md, then commits and pushes
# the changes to the current branch so the PR includes up-to-date documentation.
# PRs that don't touch worker source are skipped (no churn commit).
#
# Hook input (stdin): JSON from Claude Code with shape:
#   { "tool_name": "Bash", "tool_input": { "command": "..." }, ... }

set -euo pipefail

# ── 1. Parse stdin ────────────────────────────────────────────────────────────
INPUT="$(cat)"

# Extract the bash command that was run (requires python3 or jq)
if command -v python3 &>/dev/null; then
    BASH_CMD="$(echo "$INPUT" | python3 -c "
import json, sys
data = json.load(sys.stdin)
print(data.get('tool_input', {}).get('command', ''))
" 2>/dev/null || true)"
elif command -v jq &>/dev/null; then
    BASH_CMD="$(echo "$INPUT" | jq -r '.tool_input.command // ""' 2>/dev/null || true)"
else
    exit 0
fi

# ── 2. Check whether this was a PR creation ───────────────────────────────────
if ! echo "$BASH_CMD" | grep -qE 'gh pr (create|edit)'; then
    exit 0
fi

echo "[update-worker-docs] PR operation detected — regenerating worker documentation..."

# ── 3. Locate repo root ───────────────────────────────────────────────────────
REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

# ── 3b. Skip unless the PR actually changed worker source ─────────────────────
# The hook fires on any `gh pr create|edit`, including description-only edits.
# Regenerating + committing docs on a PR that didn't touch any worker source is
# just noise — an unrelated PR (e.g. a build-script change) would otherwise pick
# up a registry-churn commit. Only proceed when the branch's diff vs. the base
# touches workers/ or the generator itself. If no base can be determined, fall
# through and regenerate (don't silently stop producing docs).
BASE_REF=""
for ref in origin/master master origin/main main; do
    if git rev-parse --verify --quiet "$ref" >/dev/null; then BASE_REF="$ref"; break; fi
done
if [ -n "$BASE_REF" ]; then
    if git diff --name-only "${BASE_REF}...HEAD" -- workers/ generate_worker_docs.py | grep -q .; then
        echo "[update-worker-docs] Worker source changed vs ${BASE_REF}; regenerating docs."
    else
        echo "[update-worker-docs] PR changed no worker source (workers/ or generate_worker_docs.py); skipping doc regen."
        exit 0
    fi
else
    echo "[update-worker-docs] No base ref found; regenerating docs to be safe."
fi

# ── 4. Run the documentation generator ───────────────────────────────────────
if ! python3 generate_worker_docs.py; then
    echo "[update-worker-docs] ERROR: generate_worker_docs.py failed — skipping commit." >&2
    exit 0
fi

# ── 5. Commit changes if any ──────────────────────────────────────────────────
# Stage only the files the generator writes: registry.md and per-worker .md
# files. Using targeted patterns avoids accidentally staging unrelated changes
# (e.g. in-progress Python or Dockerfile edits) that happen to be uncommitted
# when the PR command runs.
git add REGISTRY.md
# Stage modified tracked .md files inside workers/
git diff --name-only -- 'workers/**/*.md' 'workers/*.md' | xargs -r git add
# Stage newly created (untracked) .md files inside workers/
git ls-files --others --exclude-standard -- 'workers/**/*.md' 'workers/*.md' | xargs -r git add

# Check whether any doc files were actually staged before committing.
# This avoids a "nothing to commit" failure when the repo has unrelated
# tracked changes but the generated docs are already up to date.
if git diff --cached --quiet; then
    echo "[update-worker-docs] Documentation is already up to date."
    exit 0
fi

echo "[update-worker-docs] Documentation changed — committing..."
git commit -m "docs: auto-update worker docs and registry.md

Regenerated by the update-worker-docs Claude Code hook after PR creation."

# ── 6. Push to the current branch ────────────────────────────────────────────
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "[update-worker-docs] Pushing docs update to origin/$BRANCH..."

for ATTEMPT in 1 2 3 4; do
    if git push origin "$BRANCH"; then
        echo "[update-worker-docs] Done — documentation pushed to origin/$BRANCH."
        exit 0
    fi
    WAIT=$(( ATTEMPT * 2 ))
    echo "[update-worker-docs] Push attempt $ATTEMPT failed; retrying in ${WAIT}s..." >&2
    sleep "$WAIT"
done

echo "[update-worker-docs] ERROR: Could not push after 4 attempts." >&2
exit 0   # Non-fatal: don't block the PR creation
