FROM nimbusimage/sam2-worker-base-m1:latest

COPY ./workers/annotations/sam2_fewshot_segmentation/entrypoint.py /

LABEL isUPennContrastWorker="" \
      isAnnotationWorker="" \
      interfaceName="SAM2 few-shot segmentation" \
      interfaceCategory="SAM2" \
      description="Uses SAM2 features for few-shot segmentation based on training annotations" \
      annotationShape="polygon" \
      defaultToolName="SAM2 few-shot"

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "worker", "python", "/entrypoint.py"]
