FROM ubuntu:jammy as base
LABEL isUPennContrastWorker=True

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -qy tzdata && \
  apt-get install -qy software-properties-common python3-software-properties && \
  apt-get update && apt-get install -qy \
  build-essential \
  wget \
  python3 \
  r-base \
  libffi-dev \
  libssl-dev \
  libjpeg-dev \
  zlib1g-dev \
  r-base \
  git \
  libpython3-dev && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# The below is for the M1 Macs and should be changed for other architectures
ENV PATH="/root/miniconda3/bin:$PATH"
ARG PATH="/root/miniconda3/bin:$PATH"

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-aarch64.sh -b \
    && rm -f Miniconda3-latest-Linux-aarch64.sh
# END M1 Mac specific

FROM base as build

COPY ./workers/annotations/ai_analysis/environment.yml /
RUN conda env create --file /environment.yml
SHELL ["conda", "run", "-n", "worker", "/bin/bash", "-c"]

# Install the annotation utilities
COPY ./annotation_utilities /annotation_utilities
WORKDIR /annotation_utilities
RUN pip install .

WORKDIR /
RUN git clone https://github.com/Kitware/UPennContrast/
WORKDIR /UPennContrast

RUN pip install -r devops/girder/annotation_client/requirements.txt
RUN pip install -e devops/girder/annotation_client/

COPY ./workers/annotations/ai_analysis/entrypoint.py /
COPY ./workers/annotations/ai_analysis/system_prompt.txt /
COPY ./workers/annotations/ai_analysis/property_handling.py /

ENV ANTHROPIC_API_KEY=""

LABEL isUPennContrastWorker="" \
      isAnnotationWorker="" \
      interfaceName="Claude natural language analyzer" \
      interfaceCategory="AI analysis" \
      description="Uses Claude AI to analyze images" \
      advancedOptionsPanel="False" \
      annotationConfigurationPanel="False" \
      defaultToolName="Claude natural language analyzer"

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "worker", "python", "/entrypoint.py"]

