FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 AS base
LABEL isUPennContrastWorker=True
LABEL com.nvidia.volumes.needed="nvidia_driver"

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -qy tzdata && \
  apt-get install -qy software-properties-common python3-software-properties && \
  apt-get update && apt-get install -qy \
  build-essential \
  wget \
  python3 \
  r-base \
  libffi-dev \
  libssl-dev \
  libjpeg-dev \
  zlib1g-dev \
  git \
  libpython3-dev && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# Miniconda3 for aarch64 (M1 Mac)
ENV PATH="/root/miniconda3/bin:$PATH"
ARG PATH="/root/miniconda3/bin:$PATH"

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-aarch64.sh -b \
    && rm -f Miniconda3-latest-Linux-aarch64.sh

# Install mamba for faster solves
RUN conda install -n base -c conda-forge mamba -y

FROM base AS build

COPY ./workers/annotations/sam_fewshot_segmentation/environment.yml /
RUN mamba env create --file /environment.yml
SHELL ["conda", "run", "-n", "worker", "/bin/bash", "-c"]

RUN pip install rtree shapely

RUN git clone https://github.com/arjunrajlaboratory/NimbusImage/
RUN pip install -r /NimbusImage/devops/girder/annotation_client/requirements.txt
RUN pip install -e /NimbusImage/devops/girder/annotation_client/

RUN wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth

COPY ./workers/annotations/sam_fewshot_segmentation/entrypoint.py /

COPY ./annotation_utilities /annotation_utilities
RUN pip install /annotation_utilities

LABEL isUPennContrastWorker="" \
      isAnnotationWorker="" \
      interfaceName="SAM few-shot segmentation" \
      interfaceCategory="SAM" \
      description="Uses SAM1 ViT-H features for few-shot segmentation based on training annotations" \
      annotationShape="polygon" \
      defaultToolName="SAM few-shot"

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "worker", "python", "/entrypoint.py"]
