FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 as base
LABEL isUPennContrastWorker=True
LABEL com.nvidia.volumes.needed="nvidia_driver"

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -qy tzdata && \
  apt-get install -qy software-properties-common python3-software-properties && \
  apt-get update && apt-get install -qy \
  build-essential \
  wget \
  python3 \
  r-base \
  libffi-dev \
  libssl-dev \
  libjpeg-dev \
  zlib1g-dev \
  r-base \
  git \
  libpython3-dev && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# The below is for the M1 Macs and should be changed for other architectures
ENV PATH="/root/miniconda3/bin:$PATH"
ARG PATH="/root/miniconda3/bin:$PATH"

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-aarch64.sh -b \
    && rm -f Miniconda3-latest-Linux-aarch64.sh
# END M1 Mac specific


FROM base as build

COPY ./workers/annotations/sam2_automatic_mask_generator/environment.yml /
RUN conda env create --file /environment.yml
SHELL ["conda", "run", "-n", "worker", "/bin/bash", "-c"]

RUN pip install rtree shapely

RUN git clone https://github.com/arjunrajlaboratory/NimbusImage/

RUN pip install -r /NimbusImage/devops/girder/annotation_client/requirements.txt
RUN pip install -e /NimbusImage/devops/girder/annotation_client/

RUN mkdir -p /code
RUN git clone https://github.com/facebookresearch/sam2.git /code/sam2
RUN pip install -e /code/sam2

# Change directory to sam2/checkpoints
WORKDIR /code/sam2/checkpoints
# Download the checkpoints into the checkpoints directory
RUN ./download_ckpts.sh
# Change back to the root directory
WORKDIR /

COPY ./workers/annotations/sam2_automatic_mask_generator/utils.py /
COPY ./workers/annotations/sam2_automatic_mask_generator/entrypoint.py /

COPY ./annotation_utilities /annotation_utilities
RUN pip install /annotation_utilities

LABEL isUPennContrastWorker="" \
      isAnnotationWorker="" \
      interfaceName="SAM2 automatic mask generator" \
      interfaceCategory="SAM2" \
      description="Uses SAM2 to find all masks in the image" \
      annotationShape="polygon" \
      defaultToolName="SAM2 mask generator"

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "worker", "python", "/entrypoint.py"]