# Use the M1 base for compatibility
FROM properties/point_to_nearest_blob_distance:latest as test

# Install test dependencies
SHELL ["conda", "run", "-n", "worker", "/bin/bash", "-c"]
RUN pip install pytest pytest-mock

# Copy test files
RUN mkdir -p /tests
COPY ./workers/properties/points/point_to_nearest_blob_distance/tests/*.py /tests
WORKDIR /tests

# Command to run tests
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "worker", "python3", "-m", "pytest", "-v"] 