name: worker
dependencies:
- python
- pip
- pip:
  - einops
  - deeptile
  - fastremap
  - flax
  - numba
  - numpy
  - opencv-python
  - scipy
  - scikit-image
  - tifffile
  - tensorflow
  - torch
  - tqdm