name: worker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - imageio
  - rasterio
  - shapely
  - pillow
  - pytorch
  - torchvision
  - opencv
  - matplotlib
  - pip:
    - segment-anything
    - pycocotools
    - onnxruntime
    - onnx