name: worker
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- pip
- numpy>=2.0
- shapely>=2.0.6
- scikit-image
- libtiff
- openslide
- libvips
# - pip:
#   - --find-links https://girder.github.io/large_image_wheels
#   - large-image[tiff]
#   - large-image-source-tiff