# Use the existing connect_to_nearest worker as the base
FROM annotations/connect_to_nearest:latest AS test

# Install test dependencies
SHELL ["conda", "run", "-n", "worker", "/bin/bash", "-c"]
RUN pip install pytest pytest-mock

# Copy test files
RUN mkdir -p /tests
COPY ./workers/annotations/connect_to_nearest/tests/*.py /tests
WORKDIR /tests

# Command to run tests
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "worker", "python3", "-m", "pytest", "-v"] 